### ISSUE TITLE
Configuration option for "M" key?

### ISSUE THREAD

**Issue by giddion** [accessible-minecraft/easy-life#1]
Can we get a config option in the file system to change the "m" key for configuration? This is getting in the way of another mod I use heavily, Litmatica

**Comment by khanshoaib3** [comment]
You can change it from the minecraft settings.

Go to options then controls then u can find the configuration key bind in the easy life section and rebind it.

**Comment by khanshoaib3** [comment]
@giddion I'll close this issue if u don't reply.

**Comment by giddion** [comment]
Sorry yes, that worked for me, close away.
